# These are supported funding model platforms

github: [alextecplayz] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: alextecplayz # Replace with a single Patreon username
ko_fi: alextecplayz # Replace with a single Ko-fi username
