title: AlexTECPlayz
email: alextec70@outlook.com
description: >- 
  My site. It has a blog.
baseurl: ""
website: https://alextecplayz.github.io
url: "https://alextecplayz.github.io"
fedicommsrv: "techhub.social"
fediusername: "@AlexTECPlayz@techhub.social"
lang: en
ver_site: 1.6.0
ver_obsidian: 1.6.0
search: true
search_full_content: true
lunr:
  search_within_pages: true

twitter_username: "@realTECPlayz"
mastodon_username: "@AlexTECPlayz@techhub.social"

author: "AlexTECPlayz"
author_description: "Alex is a developer that occasionally reviews games, software and tech, and her website includes ramblings, reviews, blog posts of any kind, and much more."

# Build settings
plugins:
  - jekyll-feed

exclude:
  - CHANGELOG.md
  - README.md
  - SECURITY.md
  - LICENSE
  - build
  - install
  - serve

include:
  - .well-known
  - _includes
  - _layouts
  - js

collections:
  en:
    output: true
    permalink: /:title

t:
    en:
        posts: Posts
        projects: Projects
        games: Games
        software: Software
        portfolio: Portfolio
        apps: Apps
        about: About
        support: Support
        uses: Uses
        notes: Notes
        search: Search
        tos: Terms of Service
        privacy: Privacy Policy
        status: Status
        present: Present
        allrights: All rights reserved.
        readmore: Read More
        postshead: 
        pagenotfound: The requested page could not be found.
        homepage: Return to the home page
        home: Index
        toc: Table of Contents
