name: Lighthouse Analysis

on:
  push:
    branches:
      - main

jobs:
  select-post:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select random post
      id: select_post
      run: |
        POSTS_DIR="_posts"
        POSTS=$(ls $POSTS_DIR/*.md | grep -v future)
        SELECTED_POST=$(shuf -n 1 -e $POSTS)
        echo "::set-output name=selected_post::$SELECTED_POST"

  lighthouse:
    needs: select-post
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: mkdir /tmp/artifacts

    - name: Run Lighthouse
      run: foo-software/lighthouse-check-action@master
       with:
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        outputDirectory: /tmp/artifacts
        urls: 'https://alextecplayz.github.io', 'https://alextecplayz.github.io/{{ steps.select-post.outputs.selected_post }}', 'https://alextecplayz.github.io/tools/monobe/map'

    - name: Upload artifacts
     uses: actions/upload-artifact@master
     with:
       name: Lighthouse reports
       path: /tmp/artifacts
